### ISSUE TITLE
Missing Default Cogwheel Recipe In Current Curseforge Version

### ISSUE THREAD

**Issue by TheElectroSheep** [Rabbitminers/Extended-Flywheels#13]
The recipe to create a default cogwheel from 1x spruce planks and 1x shaft is currently missing. Every other recipe appears to work though.
![image](https://user-images.githubusercontent.com/79412436/209811741-728c41c0-76e0-4720-b292-6adbf13a817f.png)

I looked in the recipes folder and it does appear to simply just be missing as there is a deafult_cogwheel_from_custom but no default_cogwheel

**Comment by Rabbitminers** [comment]
Having no recipe there is intentional as the old recipe had to  be overwritten which is handled by this recipe here https://github.com/Rabbitminers/Extended-Cogs/blob/1.18.2-0.5.0g/src/main/resources/data/create/recipes/crafting/kinetics/cogwheel.json. Which makes this even more odd since the old recipe for cogwheels has been removed by the new recipe but it doesnt take its place
