### ISSUE TITLE
Can't encase modded cogwheels

### ISSUE THREAD

**Issue by HeyNoose** [Rabbitminers/Extended-Flywheels#16]
Not sure if intended but using casings on modded cogwheels does nothing, only tested this with oak cogwheels.

**Comment by Rabbitminers** [comment]
This is intended to fix encased cogwheels reverting to the default ones. Adding more encased versions is planned and should be implemented soon-ish

**Comment by DoxLePup** [comment]
Cogs can now be encased however when breaking a "encased cogwheel" it doesnt drop anything. Also ive noticed in creative that block-picking the created encased cogwheel just gives you a cogwheel, not an encased cogwheel. Work around being that the wrench is able to pick it up just fine.
There is also another bug that is when you do exactly what I just mentioned, a shaftless cog is given a shaft, with no shaft needed. so you can make cogs with wood alone and then encase them (for free since encasing doesnt use up the andesite casing) it is then turned into a full cogwheel with shaft.
